---
root: true
env:
  node: true
parserOptions: {}
extends:
  - standard
plugins:
  - "@stylistic/js"
rules:
  no-console: warn
  comma-dangle:
    - error
    - arrays: ignore
      objects: ignore
      imports: never
      exports: never
      functions: never
  "@stylistic/js/quote-props":
    - error
    - consistent
  no-unused-vars:
    - error
    - varsIgnorePattern: _

#  vue/no-duplicate-attributes:
#    - error
#    - allowCoexistClass: true
#      allowCoexistStyle: true